export const rawDef = Symbol('rawDef')
export const isStruct = Symbol('isStruct')
export const isVector = Symbol('isVector')
export const isComputed = Symbol('isComputed')
export const sizeOf = Symbol('sizeOf')
